apiVersion: v1
kind: Service
metadata:
  name: website-load-balancer-service
  labels:
    name: website-load-balancer-service
    app: website
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8061
  selector:
    name: website-pod
    app: website
