apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    name: website-service
    app: website
spec:
  ports:
  - port: 8061
    targetPort: 80
  selector:
    name: website-pod
    app: website
